apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customdatabases.igor.yatsevich.ru
spec:
  group: igor.yatsevich.ru
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretName:
                  type: string
  names:
    kind: CustomDatabase
    plural: customdatabases
  scope: Namespaced
